---
manager:
  max_workers: 2
  plan_outputs:
    markdown:
      class: octodns.provider.plan.PlanMarkdown

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True
  etchosts:
    class: octodns.provider.etc_hosts.EtcHostsProvider
    directory: ./hosts

zones:
  example.com.:
    sources:
      - config
    targets:
      - etchosts
