name: octodns-sync

on:
  # Deploy config whenever DNS changes are pushed to main.
  push:

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: solvaholic/octodns-sync@main
        with:
          config_path: config/test.yaml
          doit: '--doit'
      - run: cat ./hosts
