name: octodns-sync

on:
  # Deploy config whenever DNS changes are pushed to main.
  push:
    branches: [main]
  pull_request:

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: travislikestocode/octodns-sync@57-support-multiple-runs
        with:
          config_path: config/test.yaml
          doit: ${{ github.event_name == 'pull_request'  && 'No' || '--doit' }}
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
      - run: cat ./hosts/example.com.hosts
      
      - name: Publish2
        uses: travislikestocode/octodns-sync@57-support-multiple-runs
        with:
          config_path: config/test2.yaml
          doit: ${{ github.event_name == 'pull_request'  && 'No' || '--doit' }}
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
      - run: cat ./hosts2/example.com.hosts
