name: octodns-sync

on:
  # Deploy config whenever DNS changes are pushed to main.
  push:
  pull_request:

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: solvaholic/octodns-sync@main
        with:
          config_path: config/test.yaml
          doit: ${{ github.event_name == 'pull_request'  && 'No' || '--doit' }}
          add_pr_comment: 'Yes'
      - run: cat ./hosts/example.com.hosts
