name: octodns-sync

on:
  pull_request_target:

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: travislikestocode/octodns-sync@comment-formatting
        with:
          config_path: config/test.yaml
          doit: '--doit'
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
