name: octodns-sync pull_request

on:
  pull_request:

jobs:
  sync-pr:
    name: Sync pull_request
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        doit: ['No', '--doit']
        footer: ['No', 'Yes']
    steps:
      - uses: actions/checkout@v2
      - name: octodns-sync
        uses: travislikestocode/octodns-sync@comment-formatting
        with:
          config_path: config/cfg.yaml
          doit: ${{ matrix.doit }}
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
          add_pr_comment_footer: ${{ matrix.footer }}
